<%--
  This is the master import file.  This include should never be directly referenced,
  rather, should include this file and then that include put on the .jsp page
--%>
<%@ page language="java" %>


<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jstl/fmt" %>

  <%--  fmt:formatDate  uses the formats for java.text.SimpleDateFormat  --%>
  
  <%--  fmt:formatNumber uses the formats for  java.text.DecimalFormat --%>

                              
<%@ taglib prefix="bean" uri="http://jakarta.apache.org/struts/tags-bean" %>
<%@ taglib prefix="html" uri="http://jakarta.apache.org/struts/tags-html" %>
<%@ taglib prefix="logic" uri="http://jakarta.apache.org/struts/tags-logic" %>
<%@ taglib prefix="nested" uri="http://jakarta.apache.org/struts/tags-nested" %>

<%@ taglib prefix="html-el" uri="http://jakarta.apache.org/struts/tags-html-el" %>

<%@ taglib prefix="tiles" uri="http://jakarta.apache.org/struts/tags-tiles" %>

