package org.jobcenter.constants;

public enum ClientStatusUpdateTypeEnum {

	CLIENT_UP,
	CLIENT_STOP_RETRIEVING_JOBS_AND_PAUSE_REQUESTED,
	CLIENT_STOP_RETRIEVING_JOBS_AND_PAUSE_COMPLETED,
	CLIENT_STOP_RETRIEVING_JOBS_AND_SHUTDOWN_REQUESTED,
	CLIENT_STOP_RETRIEVING_JOBS_AND_SHUTDOWN_COMPLETED,
	CLIENT_SHUTDOWN_REQUESTED,
	CLIENT_ABOUT_TO_EXIT
}
